






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace TechBlog.Site.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace TechBlog.Site.Models.sitecore.templates.TechBlog_Temp
{


 	/// <summary>
	/// IPage_Site Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Page site</para>	
	/// <para>ID: 3f7e7f57-ebf7-497c-bc03-0704446166cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_SiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage_Site : IGlassBase 
	{
			
					/// <summary>
					/// The name page field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8faa112c-4508-4159-ab9a-f13c305b6a8e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPage_SiteConstants.Name_PageFieldName)]
					string Name_Page  {get; set;}
			
			
					/// <summary>
					/// The title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a93a5815-56f3-4b39-9258-cc17ac143cff</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPage_SiteConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IPage_SiteConstants{

			public const string TemplateIdString = "3f7e7f57-ebf7-497c-bc03-0704446166cd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page site";

		
			
			public static readonly ID Name_PageFieldId = new ID("8faa112c-4508-4159-ab9a-f13c305b6a8e");
			public const string Name_PageFieldName = "name page";
			
		
			
			public static readonly ID TitleFieldId = new ID("a93a5815-56f3-4b39-9258-cc17ac143cff");
			public const string TitleFieldName = "title";
			
			

	}

	
	/// <summary>
	/// Page_Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Page site</para>	
	/// <para>ID: 3f7e7f57-ebf7-497c-bc03-0704446166cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_SiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Page_Site  : GlassBase, IPage_Site 
	{
	   
		
				/// <summary>
				/// The name page field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8faa112c-4508-4159-ab9a-f13c305b6a8e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPage_SiteConstants.Name_PageFieldName)]
				public virtual string Name_Page  {get; set;}
					
		
				/// <summary>
				/// The title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a93a5815-56f3-4b39-9258-cc17ac143cff</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPage_SiteConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace TechBlog.Site.Models.sitecore.templates.TechBlog_Temp
{


 	/// <summary>
	/// ISite_Temp Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Site Temp</para>	
	/// <para>ID: 49d985db-a1f5-48b0-881c-5c66a179b1e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_TempConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite_Temp : IGlassBase 
	{
			
					/// <summary>
					/// The description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 243873f5-c2b6-49ba-a563-7abe1b236148</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISite_TempConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The name site field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 065654d3-909e-459a-af6a-b221c986dffc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISite_TempConstants.Name_SiteFieldName)]
					string Name_Site  {get; set;}
			
			
	}


	public static partial class ISite_TempConstants{

			public const string TemplateIdString = "49d985db-a1f5-48b0-881c-5c66a179b1e1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site Temp";

		
			
			public static readonly ID DescriptionFieldId = new ID("243873f5-c2b6-49ba-a563-7abe1b236148");
			public const string DescriptionFieldName = "description";
			
		
			
			public static readonly ID Name_SiteFieldId = new ID("065654d3-909e-459a-af6a-b221c986dffc");
			public const string Name_SiteFieldName = "name site";
			
			

	}

	
	/// <summary>
	/// Site_Temp
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Site Temp</para>	
	/// <para>ID: 49d985db-a1f5-48b0-881c-5c66a179b1e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_TempConstants.TemplateIdString)] //, Cachable = true
	public partial class Site_Temp  : GlassBase, ISite_Temp 
	{
	   
		
				/// <summary>
				/// The description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 243873f5-c2b6-49ba-a563-7abe1b236148</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_TempConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The name site field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 065654d3-909e-459a-af6a-b221c986dffc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_TempConstants.Name_SiteFieldName)]
				public virtual string Name_Site  {get; set;}
					
			
	}

}
