





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace TechBlog.Site.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace TechBlog.Site.Models.sitecore.templates.TechBlog_Temp
{


 	/// <summary>
	/// IPage_Site Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Page site</para>	
	/// <para>ID: 3f7e7f57-ebf7-497c-bc03-0704446166cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_SiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage_Site : IGlassBase 
	{
								/// <summary>
					/// The name page field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8faa112c-4508-4159-ab9a-f13c305b6a8e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPage_SiteConstants.Name_PageFieldName)]
					string Name_Page  {get; set;}
			
								/// <summary>
					/// The title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a93a5815-56f3-4b39-9258-cc17ac143cff</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPage_SiteConstants.TitleFieldName)]
					string Title  {get; set;}
			
								/// <summary>
					/// The Vote Item field.
					/// <para></para>
					/// <para>Field Type: Droplist</para>		
					/// <para>Field ID: ca57a1be-862c-4180-b446-6e687dd15354</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPage_SiteConstants.Vote_ItemFieldName)]
					string Vote_Item  {get; set;}
			
				}


	public static partial class IPage_SiteConstants{

			public const string TemplateIdString = "3f7e7f57-ebf7-497c-bc03-0704446166cd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page site";

					
			public static readonly ID Name_PageFieldId = new ID("8faa112c-4508-4159-ab9a-f13c305b6a8e");
			public const string Name_PageFieldName = "name page";
			
					
			public static readonly ID TitleFieldId = new ID("a93a5815-56f3-4b39-9258-cc17ac143cff");
			public const string TitleFieldName = "title";
			
					
			public static readonly ID Vote_ItemFieldId = new ID("ca57a1be-862c-4180-b446-6e687dd15354");
			public const string Vote_ItemFieldName = "Vote Item";
			
			

	}

	
	/// <summary>
	/// Page_Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Page site</para>	
	/// <para>ID: 3f7e7f57-ebf7-497c-bc03-0704446166cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_SiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Page_Site  : GlassBase, IPage_Site 
	{
	   
						/// <summary>
				/// The name page field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8faa112c-4508-4159-ab9a-f13c305b6a8e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPage_SiteConstants.Name_PageFieldName)]
				public virtual string Name_Page  {get; set;}
					
						/// <summary>
				/// The title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a93a5815-56f3-4b39-9258-cc17ac143cff</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPage_SiteConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Vote Item field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// <para>Field ID: ca57a1be-862c-4180-b446-6e687dd15354</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPage_SiteConstants.Vote_ItemFieldName)]
				public virtual string Vote_Item  {get; set;}
					
			
	}
}
namespace TechBlog.Site.Models.sitecore.templates.TechBlog_Temp
{


 	/// <summary>
	/// ISite_Temp Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Site Temp</para>	
	/// <para>ID: 49d985db-a1f5-48b0-881c-5c66a179b1e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_TempConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite_Temp : IGlassBase 
	{
								/// <summary>
					/// The description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 243873f5-c2b6-49ba-a563-7abe1b236148</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISite_TempConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
								/// <summary>
					/// The name site field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 065654d3-909e-459a-af6a-b221c986dffc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISite_TempConstants.Name_SiteFieldName)]
					string Name_Site  {get; set;}
			
				}


	public static partial class ISite_TempConstants{

			public const string TemplateIdString = "49d985db-a1f5-48b0-881c-5c66a179b1e1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site Temp";

					
			public static readonly ID DescriptionFieldId = new ID("243873f5-c2b6-49ba-a563-7abe1b236148");
			public const string DescriptionFieldName = "description";
			
					
			public static readonly ID Name_SiteFieldId = new ID("065654d3-909e-459a-af6a-b221c986dffc");
			public const string Name_SiteFieldName = "name site";
			
			

	}

	
	/// <summary>
	/// Site_Temp
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Site Temp</para>	
	/// <para>ID: 49d985db-a1f5-48b0-881c-5c66a179b1e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_TempConstants.TemplateIdString)] //, Cachable = true
	public partial class Site_Temp  : GlassBase, ISite_Temp 
	{
	   
						/// <summary>
				/// The description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 243873f5-c2b6-49ba-a563-7abe1b236148</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_TempConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The name site field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 065654d3-909e-459a-af6a-b221c986dffc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_TempConstants.Name_SiteFieldName)]
				public virtual string Name_Site  {get; set;}
					
			
	}
}
namespace TechBlog.Site.Models.sitecore.templates.TechBlog_Temp
{


 	/// <summary>
	/// IPosts_Temp Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Posts Temp</para>	
	/// <para>ID: 6755037a-9e81-493e-86df-9c9e26464c2a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPosts_TempConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPosts_Temp : IGlassBase 
	{
								/// <summary>
					/// The content1 field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: efe34efb-210c-46b6-8686-877e0cd253cf</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Content1FieldName)]
					string Content1  {get; set;}
			
								/// <summary>
					/// The content2 field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8a0312a5-3a24-476f-a734-9f3de3827e9f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Content2FieldName)]
					string Content2  {get; set;}
			
								/// <summary>
					/// The content3 field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 59e08034-4d25-475c-a535-2499ea2aae8a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Content3FieldName)]
					string Content3  {get; set;}
			
								/// <summary>
					/// The desciption field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 218237d4-76d8-419a-8a4b-83b0982ba579</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.DesciptionFieldName)]
					string Desciption  {get; set;}
			
								/// <summary>
					/// The img banner post field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 8a23b6c5-a8b8-4e35-afec-5c3c29409a9b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Img_Banner_PostFieldName)]
					Image Img_Banner_Post  {get; set;}
			
								/// <summary>
					/// The img content1 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: dc608aa1-0f08-4fdc-8082-dc76c18fe7dc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Img_Content1FieldName)]
					Image Img_Content1  {get; set;}
			
								/// <summary>
					/// The img content2 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: ccbde96b-8ab2-4c33-9d38-9518870cc972</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Img_Content2FieldName)]
					Image Img_Content2  {get; set;}
			
								/// <summary>
					/// The img content3 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: bccbd1d6-2887-46e6-86fe-3a1c06eab29f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Img_Content3FieldName)]
					Image Img_Content3  {get; set;}
			
								/// <summary>
					/// The time post field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: 2bbca702-854b-470d-8f9d-204bf2ffee20</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Time_PostFieldName)]
					DateTime Time_Post  {get; set;}
			
								/// <summary>
					/// The title posts field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e6a321a6-6910-4333-94ce-30bc5500fb26</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPosts_TempConstants.Title_PostsFieldName)]
					string Title_Posts  {get; set;}
			
				}


	public static partial class IPosts_TempConstants{

			public const string TemplateIdString = "6755037a-9e81-493e-86df-9c9e26464c2a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Posts Temp";

					
			public static readonly ID Content1FieldId = new ID("efe34efb-210c-46b6-8686-877e0cd253cf");
			public const string Content1FieldName = "content1";
			
					
			public static readonly ID Content2FieldId = new ID("8a0312a5-3a24-476f-a734-9f3de3827e9f");
			public const string Content2FieldName = "content2";
			
					
			public static readonly ID Content3FieldId = new ID("59e08034-4d25-475c-a535-2499ea2aae8a");
			public const string Content3FieldName = "content3";
			
					
			public static readonly ID DesciptionFieldId = new ID("218237d4-76d8-419a-8a4b-83b0982ba579");
			public const string DesciptionFieldName = "desciption";
			
					
			public static readonly ID Img_Banner_PostFieldId = new ID("8a23b6c5-a8b8-4e35-afec-5c3c29409a9b");
			public const string Img_Banner_PostFieldName = "img banner post";
			
					
			public static readonly ID Img_Content1FieldId = new ID("dc608aa1-0f08-4fdc-8082-dc76c18fe7dc");
			public const string Img_Content1FieldName = "img content1";
			
					
			public static readonly ID Img_Content2FieldId = new ID("ccbde96b-8ab2-4c33-9d38-9518870cc972");
			public const string Img_Content2FieldName = "img content2";
			
					
			public static readonly ID Img_Content3FieldId = new ID("bccbd1d6-2887-46e6-86fe-3a1c06eab29f");
			public const string Img_Content3FieldName = "img content3";
			
					
			public static readonly ID Time_PostFieldId = new ID("2bbca702-854b-470d-8f9d-204bf2ffee20");
			public const string Time_PostFieldName = "time post";
			
					
			public static readonly ID Title_PostsFieldId = new ID("e6a321a6-6910-4333-94ce-30bc5500fb26");
			public const string Title_PostsFieldName = "title posts";
			
			

	}

	
	/// <summary>
	/// Posts_Temp
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/Posts Temp</para>	
	/// <para>ID: 6755037a-9e81-493e-86df-9c9e26464c2a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPosts_TempConstants.TemplateIdString)] //, Cachable = true
	public partial class Posts_Temp  : GlassBase, IPosts_Temp 
	{
	   
						/// <summary>
				/// The content1 field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: efe34efb-210c-46b6-8686-877e0cd253cf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Content1FieldName)]
				public virtual string Content1  {get; set;}
					
						/// <summary>
				/// The content2 field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8a0312a5-3a24-476f-a734-9f3de3827e9f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Content2FieldName)]
				public virtual string Content2  {get; set;}
					
						/// <summary>
				/// The content3 field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 59e08034-4d25-475c-a535-2499ea2aae8a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Content3FieldName)]
				public virtual string Content3  {get; set;}
					
						/// <summary>
				/// The desciption field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 218237d4-76d8-419a-8a4b-83b0982ba579</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.DesciptionFieldName)]
				public virtual string Desciption  {get; set;}
					
						/// <summary>
				/// The img banner post field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8a23b6c5-a8b8-4e35-afec-5c3c29409a9b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Img_Banner_PostFieldName)]
				public virtual Image Img_Banner_Post  {get; set;}
					
						/// <summary>
				/// The img content1 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: dc608aa1-0f08-4fdc-8082-dc76c18fe7dc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Img_Content1FieldName)]
				public virtual Image Img_Content1  {get; set;}
					
						/// <summary>
				/// The img content2 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: ccbde96b-8ab2-4c33-9d38-9518870cc972</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Img_Content2FieldName)]
				public virtual Image Img_Content2  {get; set;}
					
						/// <summary>
				/// The img content3 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: bccbd1d6-2887-46e6-86fe-3a1c06eab29f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Img_Content3FieldName)]
				public virtual Image Img_Content3  {get; set;}
					
						/// <summary>
				/// The time post field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: 2bbca702-854b-470d-8f9d-204bf2ffee20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Time_PostFieldName)]
				public virtual DateTime Time_Post  {get; set;}
					
						/// <summary>
				/// The title posts field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e6a321a6-6910-4333-94ce-30bc5500fb26</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPosts_TempConstants.Title_PostsFieldName)]
				public virtual string Title_Posts  {get; set;}
					
			
	}
}
namespace TechBlog.Site.Models.sitecore.templates.TechBlog_Temp
{


 	/// <summary>
	/// IStarVote Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/StarVote</para>	
	/// <para>ID: 6770d6ee-e231-4850-a931-e8aea22ab959</para>	
	/// </summary>
	[SitecoreType(TemplateId=IStarVoteConstants.TemplateIdString )] //, Cachable = true
	public partial interface IStarVote : IGlassBase 
	{
								/// <summary>
					/// The Email field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 81798a34-131e-43d3-bd38-0e7a6668c86a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IStarVoteConstants.EmailFieldName)]
					string Email  {get; set;}
			
								/// <summary>
					/// The number star field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 64fccb31-6a8c-45b4-b9f9-43946d10f53e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IStarVoteConstants.Number_StarFieldName)]
					float Number_Star  {get; set;}
			
								/// <summary>
					/// The time vote field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: c27e189a-047d-4d84-a26f-6086dc16fd4f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IStarVoteConstants.Time_VoteFieldName)]
					DateTime Time_Vote  {get; set;}
			
								/// <summary>
					/// The title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d6137184-e2e9-4e90-a139-85d66b3b272b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IStarVoteConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IStarVoteConstants{

			public const string TemplateIdString = "6770d6ee-e231-4850-a931-e8aea22ab959";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "StarVote";

					
			public static readonly ID EmailFieldId = new ID("81798a34-131e-43d3-bd38-0e7a6668c86a");
			public const string EmailFieldName = "Email";
			
					
			public static readonly ID Number_StarFieldId = new ID("64fccb31-6a8c-45b4-b9f9-43946d10f53e");
			public const string Number_StarFieldName = "number star";
			
					
			public static readonly ID Time_VoteFieldId = new ID("c27e189a-047d-4d84-a26f-6086dc16fd4f");
			public const string Time_VoteFieldName = "time vote";
			
					
			public static readonly ID TitleFieldId = new ID("d6137184-e2e9-4e90-a139-85d66b3b272b");
			public const string TitleFieldName = "title";
			
			

	}

	
	/// <summary>
	/// StarVote
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/StarVote</para>	
	/// <para>ID: 6770d6ee-e231-4850-a931-e8aea22ab959</para>	
	/// </summary>
	[SitecoreType(TemplateId=IStarVoteConstants.TemplateIdString)] //, Cachable = true
	public partial class StarVote  : GlassBase, IStarVote 
	{
	   
						/// <summary>
				/// The Email field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 81798a34-131e-43d3-bd38-0e7a6668c86a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IStarVoteConstants.EmailFieldName)]
				public virtual string Email  {get; set;}
					
						/// <summary>
				/// The number star field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 64fccb31-6a8c-45b4-b9f9-43946d10f53e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IStarVoteConstants.Number_StarFieldName)]
				public virtual float Number_Star  {get; set;}
					
						/// <summary>
				/// The time vote field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: c27e189a-047d-4d84-a26f-6086dc16fd4f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IStarVoteConstants.Time_VoteFieldName)]
				public virtual DateTime Time_Vote  {get; set;}
					
						/// <summary>
				/// The title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d6137184-e2e9-4e90-a139-85d66b3b272b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IStarVoteConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace TechBlog.Site.Models.sitecore.templates.TechBlog_Temp
{


 	/// <summary>
	/// IComment_Temp Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/comment temp</para>	
	/// <para>ID: fe16f76d-f2c0-4eb2-ac30-d877608e1dd1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComment_TempConstants.TemplateIdString )] //, Cachable = true
	public partial interface IComment_Temp : IGlassBase 
	{
								/// <summary>
					/// The comment field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 96efb95d-6bf0-44ca-8a30-29b82dc3d0b5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IComment_TempConstants.CommentFieldName)]
					string Comment  {get; set;}
			
								/// <summary>
					/// The email field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: baf8d579-f763-4f94-876a-cb911f8b835f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IComment_TempConstants.EmailFieldName)]
					string Email  {get; set;}
			
								/// <summary>
					/// The name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 476f2910-64b3-4ac6-98b1-698f31ea51fb</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IComment_TempConstants.NameFieldName)]
					string Name  {get; set;}
			
								/// <summary>
					/// The time cmt field.
					/// <para></para>
					/// <para>Field Type: Datetime</para>		
					/// <para>Field ID: b25b6a69-e0c6-4698-9155-c2409f095453</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IComment_TempConstants.Time_CmtFieldName)]
					DateTime Time_Cmt  {get; set;}
			
				}


	public static partial class IComment_TempConstants{

			public const string TemplateIdString = "fe16f76d-f2c0-4eb2-ac30-d877608e1dd1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "comment temp";

					
			public static readonly ID CommentFieldId = new ID("96efb95d-6bf0-44ca-8a30-29b82dc3d0b5");
			public const string CommentFieldName = "comment";
			
					
			public static readonly ID EmailFieldId = new ID("baf8d579-f763-4f94-876a-cb911f8b835f");
			public const string EmailFieldName = "email";
			
					
			public static readonly ID NameFieldId = new ID("476f2910-64b3-4ac6-98b1-698f31ea51fb");
			public const string NameFieldName = "name";
			
					
			public static readonly ID Time_CmtFieldId = new ID("b25b6a69-e0c6-4698-9155-c2409f095453");
			public const string Time_CmtFieldName = "time cmt";
			
			

	}

	
	/// <summary>
	/// Comment_Temp
	/// <para></para>
	/// <para>Path: /sitecore/templates/TechBlog Temp/comment temp</para>	
	/// <para>ID: fe16f76d-f2c0-4eb2-ac30-d877608e1dd1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComment_TempConstants.TemplateIdString)] //, Cachable = true
	public partial class Comment_Temp  : GlassBase, IComment_Temp 
	{
	   
						/// <summary>
				/// The comment field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 96efb95d-6bf0-44ca-8a30-29b82dc3d0b5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IComment_TempConstants.CommentFieldName)]
				public virtual string Comment  {get; set;}
					
						/// <summary>
				/// The email field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: baf8d579-f763-4f94-876a-cb911f8b835f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IComment_TempConstants.EmailFieldName)]
				public virtual string Email  {get; set;}
					
						/// <summary>
				/// The name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 476f2910-64b3-4ac6-98b1-698f31ea51fb</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IComment_TempConstants.NameFieldName)]
				public virtual string Name  {get; set;}
					
						/// <summary>
				/// The time cmt field.
				/// <para></para>
				/// <para>Field Type: Datetime</para>		
				/// <para>Field ID: b25b6a69-e0c6-4698-9155-c2409f095453</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IComment_TempConstants.Time_CmtFieldName)]
				public virtual DateTime Time_Cmt  {get; set;}
					
			
	}
}
